server:
  servlet:
    contextpath: /api

jwt:
  secret: fjshbfJKHFDSJKhfos8fp3fofSDFsf32455vdcfghdfgv34234ggdgjghjdf5345DSFSDFsfrg43
  expiration:
    ms: 86400000
    remember-me:
      ms: 2592000000

google:
  oauth:
    client-id: 857347797520-ca56rug79hdelb4ar8pdqmjtoc6v07jb.apps.googleusercontent.com

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: task_manager
      autoindexcreation: true
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 6987adaa7792481e88df
            clientSecret: aa561776aa17b81916754503600240d72743a1ff
            scope: email, public_profile
